apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "rpi-export.fullname" . }}
  labels:
    {{- include "rpi-export.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "rpi-export.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rpi-export.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rpi-export.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /rpi_exporter
          args:
          {{- if .Values.args.bindInterface }}
          - --bind-interface={{ .Values.args.bindInterface }}
          {{- end }}
          {{- if .Values.args.port }}
          - --port={{ .Values.args.port }}
          {{- end }}
          {{- if .Values.args.debugMbox }}
          - --mailbox-debug
          {{- end }}
          {{- if .Values.args.logLevel }}
          - -v={{ .Values.args.logLevel }}
          {{- end }}
          {{- if .Values.useNodeNameAsHostname }}
          env:
            - name: HOSTNAME_OVERRIDE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.args.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
