{
 "title": "UPS Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(apcupsd_info) by (hostname)"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(apcupsd_info) by (model)" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(apcupsd_info) by (status)" }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_battery_charge_percent" }
   ]
  },
  {
   "title": "Time Left on Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds"
    }
   ]
  },
  {
   "title": "Time on Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds"
    }
   ]
  },
  {
   "title": "Max Wattage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_nominal_power_watts" }
   ]
  },
  {
   "title": "Load Percent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_ups_load_percent" }
   ]
  },
  {
   "title": "Output Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "apcupsd_output_volts", "legendFormat": "Output" }
   ]
  },
  {
   "title": "Current Power Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "apcupsd_nominal_power_watts*apcupsd_ups_load_percent/100",
     "legendFormat": "Usage"
    }
   ]
  }
 ]
}