apiVersion: v1
kind: Service
metadata:
  name: {{ include "dnsfilter-relay.fullname" . }}
  labels:
    {{- include "dnsfilter-relay.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.service.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "dnsfilter-relay.selectorLabels" . | nindent 4 }}
